a=int(input("masukan nilai a:"))
b=int(input("masukan nilai b:"))
print("variable a=",a)
print("variable b=",b)
print("hasil penggabungan {0}&{1}=%d".format(a,b) %(a+b))

a=int(a)
b=int(b)
print("hasil penjumlahan {0}+{1}=%d".format(a,b) %(a+b))
print("hasil pembagian {0}/{1}=%d".format(a,b) %(a/b))
